<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div>
        <table>
            <tr>
                <th>ID</th>
                <th>nickname</th>
                <th>Email</th>
                <th>Trys</th>
            </tr>

        <#list users as user>
            <tr>
                <td>${user.id}</td>
                <td>${user.nickname}</td>
                <td>${user.email}</td>
                <td>${user.trys}</td>

            </tr>
        </#list>
        </table>
        <form action="/users" method="post">
            <input name ="myString" type="text" placeholder="guess">
            <input type="submit" value="check">
        </form>
    </div>

</body>
</html>